version: "3"
services:
  nuxt:
    build: ./
    container_name: nerovi-website
    restart: always
    ports:
      - "3333:3333"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: nerovi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
